/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const QueryInquiry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Admin = IDL.Principal;

export const idlService = IDL.Service({
  'getAllInquiries' : IDL.Func([], [IDL.Vec(QueryInquiry)], ['query']),
  'initializeAdmin' : IDL.Func([Admin], [], []),
  'isAdmin' : IDL.Func([Admin], [IDL.Bool], ['query']),
  'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const QueryInquiry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Admin = IDL.Principal;
  
  return IDL.Service({
    'getAllInquiries' : IDL.Func([], [IDL.Vec(QueryInquiry)], ['query']),
    'initializeAdmin' : IDL.Func([Admin], [], []),
    'isAdmin' : IDL.Func([Admin], [IDL.Bool], ['query']),
    'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };